#!/usr/bin/env python3
# from typing import *


# def solve(N: int, C: int, x: List[int], v: List[int]) -> int:
def solve(N, C, x, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, C = map(int, input().split())
    x = [None for _ in range(N)]
    v = [None for _ in range(N)]
    for i in range(N):
        x[i], v[i] = map(int, input().split())
    a = solve(N, C, x, v)
    print(a)


if __name__ == '__main__':
    main()
