#!/usr/bin/env python3
# from typing import *
from collections import deque

# def solve(S: str) -> Any:
def solve(S):
    counter = [0, 0]
    ans = ""
    tmp_s = ""
    for s in S:
        if s == 'A':
            counter[0] += 1
            tmp_s += 'A'
        elif s == 'B':
            if counter[0] >= 1:
                counter[1] += 1
                tmp_s += 'B'
                if counter[1] > 1:
                    ans += tmp_s
                    tmp_s = ""
                    counter[0] = 0
                    counter[1] = 0
            else:
                counter[0] = 0
                ans += tmp_s
                tmp_s = ""
                ans += 'B'
        else:
            if counter[0] >= 1 and counter[1] == 1:
                counter[0] -= 1
                counter[1] -= 1
                tmp_s = tmp_s[:len(tmp_s)-2]
            else:
                counter[0] = 0
                ans += tmp_s
                tmp_s = ""
                ans += 'C'
    ans += tmp_s
    return ans

def solve2(S):
    d = deque()
    for s in S:
        if s != 'C':
            d.append(s)
        elif len(d) >= 2:
            b = d.pop()
            a = d.pop()
            if not (a == 'A' and b == 'B'):
                d.append(a)
                d.append(b)
                d.append(s)
        else:
            d.append(s)
    ans = ""
    for _ in range(len(d)):
        ans += d.popleft()
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    ans = solve2(S)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
