#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, h: List[int]) -> int:
def solve(N, K, h):
    INF = (N-1)*10**4+1
    dp = [INF for _ in range(N)]
    dp[0] = 0
    for i in range(1, N):
        for j in range(i-1, -1, -1):
            if j < i - K: break
            cost = dp[j]+abs(h[i]-h[j])
            if dp[i] > cost:
                dp[i] = cost
    return dp[N-1]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    h = [None for _ in range(N)]
    for i in range(N):
        h[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, h)
    print(a)


if __name__ == '__main__':
    main()
