#!/usr/bin/env python3
import math

# def solve(N: int) -> int:
def solve(N):
    b = 0
    c = 0
    ii = 0
    ans_a = ""
    ans_b = ""
    ans_c = ""
    for i in range(int(math.sqrt(N)), 0, -1):
        print(i)
        a = N // i**2
        print(a)
        if a == 1:
            print(i)
            ans_a = "1" * (i+1)
            b = int(math.ceil(((i+1)**(i+1) - i**2) / 2))
            c = ((i+1)**(i+1) - i**2) // 2
            ii = i**i
            break
    ans_b = "1" * ((N - i**2) // b)
    ans_c = "1" * ((N - i**2) % b + 1)
    return int(ans_a) + int(ans_b) + int(ans_c)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
