#!/usr/bin/env python3

# def solve(N: int) -> int:
def solve(N):
    count = 0
    for a in range(4):
        for b in range(4):
            for c in range(4):
                for d in range(4):
                    for e in range(4):
                        for f in range(4):
                            for g in range(4):
                                for h in range(4):
                                    for i in range(4):
                                        for j in range(4):
                                            for k in range(4):
                                                for l in range(4):
                                                    if a+b+c+d+e+f+g+h+i+j+k+l != 3: continue
                                                    count += 1
                                                    if count == N:
                                                        ll = int('1' * 1) * l
                                                        kk = int('1' * 2) * k
                                                        jj = int('1' * 3) * j
                                                        ii = int('1' * 4) * i
                                                        hh = int('1' * 5) * h
                                                        gg = int('1' * 6) * g
                                                        ff = int('1' * 7) * f
                                                        ee = int('1' * 8) * e
                                                        dd = int('1' * 9) * d
                                                        cc = int('1' * 10) * c
                                                        bb = int('1' * 11) * b
                                                        aa = int('1' * 12) * a
                                                        return aa+bb+cc+dd+ee+ff+gg+hh+ii+jj+kk+ll
    
def base_10(num_n, n):
    num_10 = 0
    for s in str(num_n):
        num_10 *= n
        num_10 += int(s)
    return num_10

def base_n(num_10, n):
    if num_10 == 0: return 0
    str_n = ''
    while num_10:
        if num_10 % n >= 10:
            return -1
        str_n += str(num_10 % n)
        num_10 //= n
    return int(str_n[::-1])

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
