#!/usr/bin/env python3
# from typing import *
import math

# def solve(N: int, X: int, T: int) -> int:
def solve(N, X, T):
    return int(math.ceil(N / X)) * T


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, T = map(int, input().split())
    a = solve(N, X, T)
    print(a)


if __name__ == '__main__':
    main()
