#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: List[str], d: int, e: List[int], f: List[int], g: List[int]) -> List[str]:
def solve(a, b, c, d, e, f, g):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    c = [None for _ in range(a)]
    for i in range(a):
        c[i] = input()
    d = int(input())
    e = [None for _ in range(d)]
    f = [None for _ in range(d)]
    g = [None for _ in range(d)]
    for i in range(d):
        e[i], f[i], g[i] = map(int, input().split())
    h = solve(a, b, c, d, e, f, g)
    for j in range(d):
        print(h[j])


if __name__ == '__main__':
    main()
