#!/usr/bin/env python3
# from typing import *
import math, sys

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    M = math.ceil(math.log2(N))
    print(M)
    l = [[] for _ in range(M)]
    for i in range(1, N+1):
        for ii in range(M):
            if i & 1 << ii:
                l[ii].append(i)
    for friend in l:
        print(len(friend), *friend)
    res = input()[::-1]
    print(N if res == "0"*M else int(res, 2))
    sys.exit()


if __name__ == '__main__':
    main()
