#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int], b: List[int]) -> int:
def solve(n, a, b):
    ans = 1_000_000_000 * n
    for s in a:
        for g in b:
            count = 0
            for i in range(n):
                count += abs(s-a[i]) + abs(a[i]-b[i]) + abs(b[i]-g)
            if ans > count:
                ans = count
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a = [None for _ in range(n)]
    b = [None for _ in range(n)]
    for i in range(n):
        a[i], b[i] = map(int, input().split())
    a1 = solve(n, a, b)
    print(a1)


if __name__ == '__main__':
    main()
