#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(s, t):
    d = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}
    s = d[s[0]] - d[s[1]]
    t = d[t[0]] - d[t[1]]
    if s == t or s == -t or s + t == 5 or -s + t == 5 or s - t == 5 or -s - t == 5:
        return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    s = input()
    t = input()
    a = solve(s, t)
    print(a)


if __name__ == '__main__':
    main()
