#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    if S[0] != S[1]:
        if S[0] == S[2]: return 1+1
        else: return 0+1
    s = S[0]
    for i in range(2, len(S)):
        if s != S[i]: return i+1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
