#!/usr/bin/env python3
# from typing import *


# def solve(W: int, H: int, x: int, y: int) -> Tuple[float, int]:
def solve(W, H, x, y):
    ans = 0
    if x == W / 2 and y == H / 2:
        ans = 1
    return format(W*H/2.0, '.6f'), ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, H, x, y = map(int, input().split())
    c, d = solve(W, H, x, y)
    print(c, d)


if __name__ == '__main__':
    main()
