#!/usr/bin/env python3
# from typing import *
import math

# def solve(N: int, M: int, K: int) -> int:
def solve(N, M, K):
    L = 0
    R = max(N, M)*K
    lcm = math.lcm(N, M)
    while R-L > 1:
        x = (L+R)//2
        if x//N+x//M - x//lcm*2 >= K:
            R = x
        else:
            L = x
    return R


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = map(int, input().split())
    a = solve(N, M, K)
    print(a)


if __name__ == '__main__':
    main()
