#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, N: int, T: str, S: List[str]) -> int:
def solve(H, W, N, T, S):
    ans = 0
    for i in range(1, H-1):
        for j in range(1, W-1):
            if S[i][j] != ".": continue
            flag = True
            h = i
            w = j
            for t in T:
                if t == "L":
                    w -= 1
                elif t == "R":
                    w += 1
                elif t == "U":
                    h -= 1
                else:
                    h += 1
                if S[h][w] == "#":
                    flag = False
                    break
            if flag:
                ans += 1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    S = [None for _ in range(H)]
    T = input()
    for i in range(H):
        S[i] = input()
    a = solve(H, W, N, T, S)
    print(a)


if __name__ == '__main__':
    main()
