#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: str, c: str, d: List[str], e: List[str]) -> int:
def solve(a, b, c, d, e):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = next(tokens)
    d = [None for _ in range(b)]
    e = [None for _ in range(b)]
    c = next(tokens)
    for i in range(b):
        d[i] = next(tokens)
        e[i] = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c, d, e)
    print(a1)


if __name__ == '__main__':
    main()
