#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, N: int) -> List[str]:
def solve(H, W, N):
    S = [["." for _ in range(W)] for _ in range(H)]
    next = 0
    now = {"h": 0, "w": 0}
    for _ in range(N):
        h = now["h"]
        w = now["w"]
        if S[h][w] == ".":
            S[h][w] = "#"
            next = (next+1) % 4
        else:
            S[h][w] = "."
            next = (next-1+4) % 4
        if next == 0:
            h = (h-1+H) % H
        elif next == 1:
            w = (w+1) % W
        elif next == 2:
            h = (h+1) % H
        else:
            w = (w-1+W) % W
        now["h"] = h
        now["w"] = w
    for s in S:
        print("".join(s))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    solve(H, W, N)


if __name__ == '__main__':
    main()
