#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(X: int, Y: int) -> int:
def solve(X, Y):
    if X > Y:
        tmp = X
        X = Y
        Y = tmp
    ans = 1
    if X % 2 == 0:
        for n in range(0, X+1, 2):
            if int((X-n)/2) + n*2 == Y:
                return com(int((X-n)/2)+n, n) % MOD
    else:
        for n in range(1, X+1, 2):
            if int((X-n)/2) + n*2 == Y:
                return com(int((X-n)/2)+n, n) % MOD
    return 0

def com(x, y):
  p, q = 1, 1
  for i in range(y):
    p = p * (x - i) % MOD
    q = q * (i + 1) % MOD
  return p * pow(q, -1, MOD) % MOD

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y = map(int, input().split())
    a = solve(X, Y)
    print(a)


if __name__ == '__main__':
    main()
