#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    ans = 0
    count = 0
    acgt = ["A", "C", "G", "T"]
    for s in S:
        if s in acgt:
            count += 1
        else:
            count = 0
        if ans < count:
            ans = count
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
