#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, a: List[int]) -> int:
def solve(N, K, a):
    sum_l = []
    sum = 0
    ans = 0
    for v in a:
        sum += v
        sum_l.append(sum)
    for i in range(len(sum_l)):
        left = 0
        right = i
        while left < right:
            mid = (left + right) // 2
            if sum_l[mid] < K:
                left = mid + 1
            else:
                right = mid
        ans += len(sum_l) - mid
                
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, K, a)
    print(a1)


if __name__ == '__main__':
    main()
