#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: str, c: List[str], d: List[List[str]]) -> int:
def solve(N, M, A):
    ans = 0
    for i in range(M):
        for j in range(M):
            if i == j: continue
            point = 0
            for k in range(N):
                if A[k][i] > A[k][j]:
                    point += A[k][i]
                else:
                    point += A[k][j]
            if ans < point:
                ans = point
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [[None for _ in range(M)] for _ in range(N)]
    for i in range(N):
        for j in range(M):
            A[i][j] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, M, A)
    print(a1)


if __name__ == '__main__':
    main()
