#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::pair<int64_t, int64_t> solve(auto N, auto M, const std::vector<auto> &A, const std::vector<auto> &B, const std::vector<auto> &C, const std::vector<auto> &D) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M;
    std::cin >> N >> M;
    std::vector<auto> A(M), B(M), C(M), D(M);
    REP (i, M) {
        std::cin >> A[i] >> B[i] >> C[i] >> D[i];
    }
    auto [c, d] = solve(N, M, A, B, C, D);
    std::cout << c << ' ' << d << '\n';
    return 0;
}
