#!/usr/bin/env python3
# from typing import *


# def solve(s: str, t: str) -> Any:
def solve(s, t):
    dp = [[0 for _ in range(3001)] for _ in range(3001)]
    for i in range(len(s)):
        for j in range(len(t)):
            if (s[i] == t[j]):
                dp[i+1][j+1] = dp[i][j] + 1
            else:
                if dp[i+1][j] >= dp[i][j+1]:
                    dp[i+1][j+1] = dp[i+1][j]
                else:
                    dp[i+1][j+1] = dp[i][j+1]
    
    # 文字列復元
    i = len(s)
    j = len(t)
    ans = ""
    while i > 0 and j > 0:
        if dp[i][j] == dp[i-1][j]:
            i -= 1
        elif dp[i][j] == dp[i][j-1]:
            j -= 1
        else:
            # s[i-1] == t[j-1] なのでどちらでも良い
            ans = s[i-1] + ans
            i -= 1
            j -= 1
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    t = input()
    ans = solve(s, t)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
