#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, S: str, l: List[int], r: List[int]) -> List[str]:
def solve(N, Q, S, l, r):
    sum_l = [0]
    sum = 0
    before = S[0]
    for i in range(1, N):
        if before == S[i]:
            sum += 1
        sum_l.append(sum)
        before = S[i]
    for i in range(Q):
        print(sum_l[r[i]-1]-sum_l[l[i]-1])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    S = input()
    for i in range(Q):
        l[i], r[i] = map(int, input().split())
    solve(N, Q, S, l, r)


if __name__ == '__main__':
    main()
