#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: str, c: List[str], d: List[List[str]], e: List[str]) -> Any:
def solve(a, b, c, d, e):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = next(tokens)
    c = [None for _ in range(b)]
    d = [[None for _ in range(c_i)] for _ in range(b)]
    e = [None for _ in range(b)]
    for i in range(b):
        c[i] = next(tokens)
        for j in range(c_i):
            d[i][j] = next(tokens)
        e[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(a, b, c, d, e)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
