#!/usr/bin/env python3
# from typing import *


# def solve(N: str, A: List[str], Q: str, X: List[str], Y: List[str]) -> Any:
def solve(N, A, Q, X, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = next(tokens)
    Q = next(tokens)
    X = [None for _ in range(Q)]
    Y = [None for _ in range(Q)]
    for i in range(Q):
        X[i] = next(tokens)
        Y[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, A, Q, X, Y)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
