#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, A: List[int], B: List[int]) -> str:
def solve(N, M, A, B):
    d = {}
    for i in range(M):
        if A[i] in d:
            if d[A[i]] == 0:
                if B[i] in d:
                    if d[B[i]] == 0: return NO
                else:
                    d[B[i]] = 1
            else:
                if B[i] in d:
                    if d[B[i]] == 1: return NO
                else:
                    d[B[i]] = 0
        else:
            if B[i] in d:
                if d[B[i]] == 0:
                    d[A[i]] = 1
                else:
                    d[A[i]] = 0
            else:
                d[A[i]] = 1
                d[B[i]] = 0
    return YES
            


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    for i in range(M):
        A[i] = int(next(tokens))
    for i in range(M):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, A, B)
    print(a)


if __name__ == '__main__':
    main()
