#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10)  # TODO: edit here
    b = random.randint(1, 10)  # TODO: edit here
    c = [None for _ in range(b)]
    d = [[None for _ in range(b)] for _ in range(b)]
    for i in range(b):
        c[i] = random.randint(1, 10)  # TODO: edit here
        for j in range(b):
            d[i][j] = random.randint(1, 10)  # TODO: edit here
    print(a)
    print(b)
    for i in range(b):
        print(c[i], *[d[i][j] for j in range(b)])


if __name__ == "__main__":
    main()
