#!/usr/bin/env python3
# from typing import *


# def solve(r: int) -> int:
def solve(r):
    return r**2


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    r = int(input())
    a = solve(r)
    print(a)


if __name__ == '__main__':
    main()
