#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string NO = "No";
std::string solve(int64_t N, int M, const std::vector<int64_t> &U, const std::vector<int64_t> &V, const std::vector<int64_t> &W) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M;
    std::cin >> N >> M;
    std::vector<int64_t> U(M), V(M), W(M);
    REP (i, M) {
        std::cin >> U[i] >> V[i] >> W[i];
    }
    auto ans = solve(N, M, U, V, W);
    std::cout << ans << '\n';
    return 0;
}
