#!/usr/bin/env python3
# from typing import *


# def solve(K: int) -> int:
def solve(K):
    ans_list = []
    for bit in range(1, 1<<10):
        b = 1
        s = ""
        for i in range(10):
            if bit & b:
                s = str(i) + s
            b <<= 1
        ans_list.append(int(s))
    ans_list.sort()
    # 本来はインデックスとしてはK-1番目だが、リストの先頭に不要な0が入っていて1つずれているためK番目
    return ans_list[K]

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    a = solve(K)
    print(a)


if __name__ == '__main__':
    main()
