#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, S: str) -> str:
def solve(N, S):
    len_s = len(S)
    S += "z"
    for i in range(len_s):
        if S[i] == "a":
            if S[i+1] == "b": return YES
        elif S[i] == "b":
            if S[i+1] == "a": return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
