#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    if not (65 <= ord(S[0]) and ord(S[0]) <= 90): return NO
    for i in range(1, len(S)):
        if not (97 <= ord(S[i]) and ord(S[i]) <= 122): return NO
    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
