#!/usr/bin/env python3
# from typing import *
from collections import deque

# def solve(H: int, W: int, K: int, S: List[str]) -> int:
def solve(H, W, K, S):
    ans = 10**9
    d = deque()
    for i in range(H):
        dot = 0
        o = 0
        d.clear()
        for j in range(W):
            if S[i][j] == "o":
                o += 1
                d.append("o")
                if len(d) > K:
                    t = d.popleft()
                    if t == "o":
                        o -= 1
                    else:
                        dot -= 1
                if dot + o >= K:
                    if ans > K-o and K-o >= 0:
                        ans = K-o
            elif S[i][j] == "x":
                dot = 0
                o = 0
                d.clear()
            else:
                dot += 1
                d.append(".")
                if len(d) > K:
                    t = d.popleft()
                    if t == "o":
                        o -= 1
                    else:
                        dot -= 1
                if dot + o >= K:
                    if ans > K-o and K-o >= 0:
                        ans = K-o
    for j in range(W):
        dot = 0
        o = 0
        d.clear()
        for i in range(H):
            if S[i][j] == "o":
                o += 1
                d.append("o")
                if len(d) > K:
                    t = d.popleft()
                    if t == "o":
                        o -= 1
                    else:
                        dot -= 1
                if dot + o >= K:
                    if ans > K-o and K-o >= 0:
                        ans = K-o
            elif S[i][j] == "x":
                dot = 0
                o = 0
                d.clear()
            else:
                dot += 1
                d.append(".")
                if len(d) > K:
                    t = d.popleft()
                    if t == "o":
                        o -= 1
                    else:
                        dot -= 1
                if dot + o >= K:
                    if ans > K-o and K-o >= 0:
                        ans = K-o
    return -1 if ans == 10**9 else ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, K = map(int, input().split())
    S = [None for _ in range(H)]
    for i in range(H):
        S[i] = input()
    a = solve(H, W, K, S)
    print(a)


if __name__ == '__main__':
    main()
