#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, m: List[int]) -> int:
def solve(N, X, m):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    m = [None for _ in range(N)]
    for i in range(N):
        m[i] = int(input())
    a = solve(N, X, m)
    print(a)


if __name__ == '__main__':
    main()
