#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> List[str]:
def solve(N, A):
    d = {}
    for i in range(N):
        d[A[i]] = i+1
    
    ans = [d[-1]]
    key = d[-1]
    i = 0
    while i+1 < N:
        ans.append(d[key])
        key = d[key]
        i += 1
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, A)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
