#!/usr/bin/env python3
# from typing import *


# def solve(Q: int, K: List[int]) -> Tuple[List[str], List[List[str]]]:
def solve(Q, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    K = [None for _ in range(Q)]
    for i in range(Q):
        K[i] = int(input())
    a, c = solve(Q, K)
    for i in range(Q):
        print(a[i], *[c[i][j] for j in range(a_i)])


if __name__ == '__main__':
    main()
