#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> int:
def solve(N, S):
    flag = [False]*3
    for i, s in enumerate(S):
        if s == 'A':
            flag[0] = True
        elif s == 'B':
            flag[1] = True
        else:
            flag[2] = True
        if flag[0] == True and flag[1] == True and flag[2] == True:
            return i+1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
