#!/usr/bin/env python3
# from typing import *


# def solve(N: int, h: List[int]) -> int:
def solve(N, h):
    INF = (N-1)*10**4+1
    dp = [INF for _ in range(N)]
    dp[0] = 0
    dp[1] = abs(h[1]-h[0])
    for i in range(2, N):
        if dp[i] > dp[i-2]+abs(h[i]-h[i-2]):
            dp[i] = dp[i-2]+abs(h[i]-h[i-2])
        if dp[i] > dp[i-1]+abs(h[i]-h[i-1]):
            dp[i] = dp[i-1]+abs(h[i]-h[i-1])
    return dp[N-1]

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    h = [None for _ in range(N)]
    for i in range(N):
        h[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, h)
    print(a)


if __name__ == '__main__':
    main()
