#!/usr/bin/env python3
# from typing import *
import math

# def solve(A: int, M: int, L: int, R: int) -> int:
def solve(A, M, L, R):
    count = 0
    if (L-A)%M == 0:
        count += 1
    if (R-A)%M == 0:
        count += 1
    if count == 0 or count == 1:
        return math.ceil((R-L)/M)
    else:
        return math.floor((R-L)/M)+1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, M, L, R = map(int, input().split())
    a = solve(A, M, L, R)
    print(a)


if __name__ == '__main__':
    main()
