#!/usr/bin/env python3
# from typing import *


# def solve(a: str) -> Tuple[int, int]:
def solve(a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    d, e = solve(a)
    print(d)
    print(e)


if __name__ == '__main__':
    main()
