#!/usr/bin/env python3
# from typing import *


# def solve(X: int, A: int) -> int:
def solve(X, A):
    if X < A:
        return 0
    return 10


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, A = map(int, input().split())
    a = solve(X, A)
    print(a)


if __name__ == '__main__':
    main()
