#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
def solve(n, a, x):
    ans = 1
    sum = 0
    for l in a:
        sum += l
        if x < sum:
            return ans
        ans += 1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n, x = map(int, input().split())
    a = list(map(int, input().split()))
    a = solve(n, a, x)
    print(a)


if __name__ == '__main__':
    main()
