#!/usr/bin/env python3
# from typing import *
from collections import deque

YES = 'Yes'
NO = 'No'


# def solve(N: int, A: List[int], B: List[int]) -> str:
def solve(N, A, B):
    l = [-1]*N*2
    stack = [-1]*N*2
    for i in range(N):
        a = 0
        b = 0
        if A[i] <= B[i]:
            a = A[i]
            b = B[i]
        else:
            a = B[i]
            b = A[i]
        l[a-1] = i
        stack[a-1] = 0
        l[b-1] = i
        stack[b-1] = 1
    d = deque()
    for i in range(2*N):
        if stack[i] == 0:
            d.append(l[i])
        elif stack[i] == 1:
            if d.pop() != l[i]: return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    a = solve(N, A, B)
    print(a)


if __name__ == '__main__':
    main()
